---

# For NTP stuff
ntp_package: ntp
ntp_enabled: true
ntp_tinker_panic: true
ntp_timezone: America/Vancouver
ntp_manage_config: true
ntp_servers:
  - "192.168.11.1 iburst"

# For docker stuff

docker_edition: 'ce'
docker_package: "docker-{{ docker_edition }}"
docker_package_state: present

# Service options.
docker_service_state: started
docker_service_enabled: true

# Docker Compose options.
docker_install_compose: true
docker_compose_version: "1.25.5"
docker_compose_path: /usr/local/bin/docker-compose

docker_apt_release_channel: stable
docker_apt_arch: amd64
docker_apt_repository: "deb [arch={{ docker_apt_arch }}] https://download.docker.com/linux/{{ ansible_distribution|lower }} {{ ansible_distribution_release }} {{ docker_apt_release_channel }}"
docker_apt_ignore_key_error: true
